micronaut:
  application:
    name: mlb-challenge
  router:
    static-resources:
      swagger:
        paths: classpath:META-INF/swagger
        mapping: /swagger/**
      swagger-ui:
        enabled: true
        paths: classpath:META-INF/swagger/views/swagger-ui
        mapping: /swagger-ui/**
datasources:
  default:
    dialect: MYSQL
    driverClassName: com.mysql.cj.jdbc.Driver
flyway:
  datasources:
    default:
      enabled: true